### ISSUE TITLE
Does it work with @custom-media ? 

### ISSUE THREAD

**Issue by sandrina-p** [GitScrum/postcss-at-rules-variables#142]
I'm using [postcss-math](https://github.com/shauns/postcss-math) with this example.

```css
:root {
    --breakpoint-xs: resolve(468 * 1 / 16)em /* -> 29.25em */
}

@custom-media --viewport-xs (width > 29.25em); /* it works */
@custom-media --viewport-xs (width > var(--breakpoint-xs) /* it doesn't work */
```

How can I make this work with `@custom-media`?
