### ISSUE TITLE
[fix]: Does not parse nested variables

### ISSUE THREAD

**Issue by MaxMilton** [GitScrum/postcss-at-rules-variables#181]
I had a look through the existing Github issues but I couldn't find this mention (which is surprising as I would think it's common).

When using nested CSS variables this plugin only replaces the first variable.

## Example

```css
:root {
  --color: blue;

  --nested-variable: var(--color);
}

@whateverAtRule var(--nested-variable);
```

Current result:

```css
@whateverAtRule var(--color);
```

Expected:

```css
@whateverAtRule blue;
```

## Workaround

In case anyone is also having this issue, a quick workaround for now is to use the plugin twice, so it resolves the at rule variable twice.

`.postcssrc.js`:
```javascript
module.exports = {
  plugins: [
    require("postcss-at-rules-variables"),
    require("postcss-at-rules-variables")
  ]
};
```
